config/routes.rb
PatchApp::Application.routes.draw do
  resources :data_patches

  match '/dashboard' => 'dashboard#show'

  match '/auth/:provider/callback' => 'authentications#create'
  devise_for :users, :path => 'accounts', :controllers => {:registrations => 'registrations'}

  match '/auth/failure' => 'Dashboard#show'
  resources :authentications, :branches

  
  root :to => "Dashboard#show"

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
end

app/models/branch.rb
class Branch < ActiveRecord::Base
  has_and_belongs_to_many :plans
  has_and_belongs_to_many :coupons

  def self.branch_id_from_subdomain(subdomain)
    # replace this by searching for a parent branch with subdomain set in the short name
    # TODO
    id = case subdomain
          when 'wf'   then 1
          when 'jpn'  then 2
          when 'bll'  then 3
          when 'in'   then 4
          when 'kn'   then 7
          when 'hsr'  then 8
          when 'ft'   then 10
          when 'kor'  then 11
          when 'jn'   then 14
          when 'ne'   then 15
          when 'rmv'  then 16
          when 'dmb'  then 19
          when 'aun'  then 20
          when 'ecil' then 21
          when 'mlm'  then 25
          when 'vij'  then 26
          when 'vjn'  then 31
          when 'rrn'  then 33
          when 'skn'  then 35
          when 'wnr'  then 36  
          else 801
          end
    id
  end
  
  def self.branch_name_from_subdomain(subdomain)
    find(branch_id_from_subdomain(subdomain)).name
  end
  
  def self.branch_from_subdomain(subdomain)
    find(branch_id_from_subdomain(subdomain))
  end
  
  def self.associate_branches(subdomain)
    branch_id = branch_id_from_subdomain(subdomain)
    if branch_id == 801
      find(:all, :conditions => ['category IN(? , ?, ?)', 'H','W','T'])
    else
      find(:all, :conditions => ['parent_id = ?', branch_id])
    end
  end
  
  def self.strata_branches 
    find(:all, :conditions => ['category IN(? , ?, ?)', 'H','W','T'])
  end

end

app/models/data_patch.rb
class DataPatch < ActiveRecord::Base
end

app/models/db_list.rb
class DbList < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authentications
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessor :current_branch
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me

  def apply_omniauth(omniauth)
    self.email = omniauth['user_info']['email'] if email.blank?
    self.username = omniauth['user_info']['name'] if username.blank?

    authentications.build(:provider => omniauth['provider'], :uid => omniauth['uid'])
  end

  def password_required?
    (authentications.empty? || !password.blank?) && super
  end

  def strata_employee?
    email.gsub(/.*@/,'').split('.').include?('strata')
  end

  def subdomain
    email.gsub(/.*@/,'').split('.')[0]
  end

  def frontoffice?
    email.split('@')[0].downcase.eql?('frontoffice')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  skip_filter :authenticate_user!

  def index
    @authentications = current_user.authentications if current_user
  end

  def create
    omniauth = request.env['omniauth.auth']
    authentication = Authentication.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
    if authentication
      flash[:notice] = 'Signed In Successful'
      sign_in_and_redirect(:user, authentication.user)
    elsif current_user
      current_user.authentications.create(:provider => omniauth['provider'], :uid => omniauth['uid'])
      flash[:notice] = 'Authentication Successful'
      redirect_to authentications_url
    else
      user = User.new
      user.apply_omniauth(omniauth)
      if user.save
        flash[:notice] = 'Signed In Successful'
        sign_in_and_redirect(:user, user)
      else
        session[:omniauth] = omniauth.except('extra')
        redirect_to new_user_registration_url
      end
    end
  end

  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy
    flash[:notice] = 'Successfully destroyed Authentication.'
    redirect_to authentications_url
  end

end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  def show
    @branch = Branch.find(params[:id])
  end

  def index
    if params[:card_id].blank?
      @branches = Branch.all
      respond_to do |format|
        format.html { }
        format.xml  { render :xml => @branches }
      end
    else
      @branch = Branch.find_by_card_id(params[:card_id])
      respond_to do |format|
        if @branch.nil?
          format.html { redirect_to branches_path }
          format.xml  { render :xml => @branch }
        else
          format.html { render :show unless @branch.nil? }
          format.xml  { render :xml => @branch }
        end
      end
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    if params[:current_branch].blank?
      user_session['current_branch'] = Branch.branch_from_subdomain(current_user.subdomain)
    else
      user_session['current_branch'] = Branch.find(params[:current_branch].to_i)
    end
    @associate_branches = Branch.associate_branches(current_user.subdomain)
  end
end

app/controllers/data_patches_controller.rb
class DataPatchesController < ApplicationController
  # GET /data_patches
  # GET /data_patches.xml
  def index
    @data_patches = DataPatch.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @data_patches }
    end
  end

  # GET /data_patches/1
  # GET /data_patches/1.xml
  def show
    @data_patch = DataPatch.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @data_patch }
    end
  end

  # GET /data_patches/new
  # GET /data_patches/new.xml
  def new
    @data_patch = DataPatch.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @data_patch }
    end
  end

  # GET /data_patches/1/edit
  def edit
    @data_patch = DataPatch.find(params[:id])
  end

  # POST /data_patches
  # POST /data_patches.xml
  def create
    @data_patch = DataPatch.new(params[:data_patch])

    respond_to do |format|
      if @data_patch.save
        format.html { redirect_to(@data_patch, :notice => 'Data patch was successfully created.') }
        format.xml  { render :xml => @data_patch, :status => :created, :location => @data_patch }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @data_patch.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /data_patches/1
  # PUT /data_patches/1.xml
  def update
    @data_patch = DataPatch.find(params[:id])

    respond_to do |format|
      if @data_patch.update_attributes(params[:data_patch])
        format.html { redirect_to(@data_patch, :notice => 'Data patch was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @data_patch.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /data_patches/1
  # DELETE /data_patches/1.xml
  def destroy
    @data_patch = DataPatch.find(params[:id])
    @data_patch.destroy

    respond_to do |format|
      format.html { redirect_to(data_patches_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    super
    session[:omniauth] = nil unless @user.new_record?
  end

  private

  def build_resource(*args)
    super
    if session[:omniauth]
      @user.apply_omniauth(session[:omniauth])
      @user.valid?
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = "Strata Retail - Just Books Community Library Chain"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/data_patches_helper.rb
module DataPatchesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/authentications/create.html.erb
<h1>Authentications#create</h1>
<p>Find me in app/views/authentications/create.html.erb</p>

app/views/authentications/destroy.html.erb
<h1>Authentications#destroy</h1>
<p>Find me in app/views/authentications/destroy.html.erb</p>

app/views/authentications/index.html.erb
<% if @authentications %>
  <% unless @authentications.empty? %>
    <p><strong>You can sign in to this account using:</strong></p>
    <div class="authentications">
      <% for authentication in @authentications %>
        <div class="authentication">
          <%= image_tag "#{authentication.provider}_32.png", :size => "32x32" %>
          <div class="provider"><%= authentication.provider.titleize %></div>
          <div class="uid"><%= authentication.uid %></div>
          <%= link_to "X", authentication, :confirm => 'Are you sure you want to remove this authentication option?', :method => :delete, :class => "remove" %>
        </div>
      <% end %>
      <div class="clear"></div>
    </div>
  <% end %>
  <p><strong>Add another service to sign in with:</strong></p>
<% else %>
  <p><strong>Sign in through one of these services:</strong></p>
<% end %>

<a href="/auth/strata" class="auth_provider">
  <%= image_tag "google_64.png", :size => "64x64", :alt => "Google" %>
  Strata
</a>
<a href="/auth/indiranagar" class="auth_provider">
  <%= image_tag "google_64.png", :size => "64x64", :alt => "Google" %>
  IndiraNagar
</a>
<a href="/auth/whitefield" class="auth_provider">
  <%= image_tag "google_64.png", :size => "64x64", :alt => "Google" %>
  Whitefield
</a>
<div class="clear"></div>

app/views/dashboard/show.html.erb
<%= javascript_tag :defer => 'defer' do -%>
	$('#current_branch').html('<%= user_session['current_branch'].name %>');
<% end -%>

  <div class='notice'>
    You are a staff of <b><%= Branch.branch_name_from_subdomain(current_user.subdomain) %>.</b>
    If this is not correct, call tech support.
    <br/>
    You are currently logged into <%= user_session['current_branch'].name %>.
    <% if  @associate_branches.length > 1 -%>
      <hr/>
      Click on any of the following branches to change your current branch.
      <br/>
      <ol>
      <% @associate_branches.each do |b| -%>
        <li><%= link_to b.name, dashboard_path(:current_branch => b.id), :confirm => "Are you sure you want to change the branch to #{b.name}?" %></li>
      <% end -%>
      </ol>
    <% end -%>
  </div>

  <% if current_user.frontoffice? -%>
    <div class='alert'>
      You logged in with <%= current_user.email %>, instead use the id that was created for you.
    </div>
  <% end -%>

  <div class='span-24' style='height:10px'></div>

  <br/><br/><br/>
  <div>
    <%= link_to 'Patch App', data_patches_path %>
  </div>
  

app/views/data_patches/_edit_form.html.erb
<%= form_for(@data_patch) do |f| %>
  <% if @data_patch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@data_patch.errors.count, "error") %> prohibited this data_patch from being saved:</h2>

      <ul>
      <% @data_patch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <span class="span-1"><%= f.label :db %></span>
    <%= f.collection_select(:db, DbList.find(:all), :db_name, :db_name, {:include_blank => 'Select Database'} ) %>
  </div>

  <div class="field">
    <%= f.label :patch %><br />
    <%= f.text_area :patch, :rows => 4, :cols => 60, :maxlength => 140 %>
  </div>

  <div class="field">
    <%= f.label :analysis %><br />
    <%= f.text_area :analysis, :rows => 4, :cols => 60, :maxlength => 140 %>
  </div>

  <div class="field">
    <%= f.label :otrs_id %><br />
    <%= f.text_field :otrs_id %>
  </div>
  <div class="field">
    <span class="span-3"><%= f.label :status %></span>
    <span class="span-3"><%= f.radio_button "status", "Open", {:checked => true} %>  Open</span>
    <span class="span-3"><%= f.radio_button "status", "Closed" %>  Closed</span>
  </div>
  <br/><br/>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/data_patches/_form.html.erb
<%= form_for(@data_patch) do |f| %>
  <% if @data_patch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@data_patch.errors.count, "error") %> prohibited this data_patch from being saved:</h2>

      <ul>
      <% @data_patch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <span class="span-1"><%= f.label :db %></span>
    <%= f.collection_select(:db, DbList.find(:all), :db_name, :db_name, {:include_blank => 'Select Database'} ) %>
  </div>

  <div class="field">
    <%= f.label :patch %><br />
    <%= f.text_area :patch, :rows => 4, :cols => 60, :maxlength => 140 %>
  </div>

  <div class="field">
    <%= f.label :analysis %><br />
    <%= f.text_area :analysis, :rows => 4, :cols => 60, :maxlength => 140 %>
  </div>

  <div class="field">
    <%= f.label :otrs_id %><br />
    <%= f.text_field :otrs_id %>
  </div>
  <div class="field">
    <span class="span-3"><%= f.label :status %></span>
    <span class="span-3"><%= f.radio_button "status", "Open",
      {:checked => true} %>  Open</span>
    
  </div>
  <br/><br/>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/data_patches/edit.html.erb
<h3>Editing Patch</h3>

<%= render 'edit_form' %>

<%= link_to 'Show', @data_patch %> |
<%= link_to 'Back', data_patches_path %>

app/views/data_patches/index.html.erb
<%= javascript_tag :defer => 'defer' do -%>
	$('#current_branch').html('<%= user_session['current_branch'].name %>');
<% end -%>

        <h3>Listing Patches</h3>

<table>
  <tr>
    <th>Db</th>
    <th>Patch</th>
    <th>Analysis</th>
    <th>Otrs</th>
    <th>Status</th>
    <th>Show</th>
    <th>Edit</th>
    <th>Destroy</th>
  </tr>

<% @data_patches.each do |data_patch| %>
  <tr>
    <td><%= data_patch.db %></td>
    <td><%= data_patch.patch %></td>
    <td><%= data_patch.analysis %></td>
    <td><%= data_patch.otrs_id %></td>
    <td><%= data_patch.status %></td>
    <td><%= link_to 'Show', data_patch %></td>
    <td><%= link_to 'Edit', edit_data_patch_path(data_patch) %></td>
    <td><%= link_to 'Destroy', data_patch, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Data patch', new_data_patch_path %>

app/views/data_patches/new.html.erb
<%= javascript_tag :defer => 'defer' do -%>
	$('#current_branch').html('<%= user_session['current_branch'].name %>');
<% end -%>

        <h3>New Patch</h3>

<%= render 'form' %>

<%= link_to 'Back', data_patches_path %>

app/views/data_patches/show.html.erb
<%= javascript_tag :defer => 'defer' do -%>
	$('#current_branch').html('<%= user_session['current_branch'].name %>');
<% end -%>

        <p id="notice"><%= notice %></p>

<p>
  <b>Db:</b>
  <%= @data_patch.db %>
</p>

<p>
  <b>Patch:</b>
  <%= @data_patch.patch %>
</p>

<p>
  <b>Analysis:</b>
  <%= @data_patch.analysis %>
</p>

<p>
  <b>Otrs:</b>
  <%= @data_patch.otrs_id %>
</p>

<p>
  <b>Status:</b>
  <%= @data_patch.status %>
</p>


<%= link_to 'Edit', edit_data_patch_path(@data_patch) %> |
<%= link_to 'Back', data_patches_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag 'screen.css', :media => 'screen,projection' %>
  <%= stylesheet_link_tag 'print.css', :media => 'print' %>

  <!--[if lt IE 8]><stylesheet_link_tag 'ie.css' media='screen, projection'><![endif]-->

  <%= stylesheet_link_tag 'plugins/fancy-type/screen.css', :media => 'screen, projection' %>
  <%= stylesheet_link_tag 'application.css', :media => 'screen,projection' %>
	<%= stylesheet_link_tag 'jquery.jscrollpane.css', :media => 'screen,projection' %>

	<%= stylesheet_link_tag 'http://cdn.webrupee.com/font', :media=>'screen,projection' %>

  <%= javascript_include_tag :defaults %>
	<%= javascript_include_tag 'jit' %>
	<%= javascript_include_tag 'jquery.jscrollpane.min.js'%>
	<%= javascript_include_tag 'jquery.printElement.min.js'%>

  <%= csrf_meta_tag %>

	<script type="text/javascript">
	    $(document).ready(function() {
					$('.scroll-pane').jScrollPane();
	        <%= yield :javascript %>
	    });
	</script>

</head>

<body>

<div class="container">
	<div class="span-24">
		<p class="masthead"><%= image_tag('JustBooks.gif', :id => 'logo', :size => '253x56')%></p>
	</div>
  <% if user_signed_in? -%>
    <div id="user_login_box" class="span-11 push-13 last">
      <span> <span id='current_branch'><%= current_user.current_branch.name if current_user.current_branch %></span> | <%= current_user.email %> |
      <%= link_to 'My info', edit_user_registration_path %> |
      <%= link_to 'Sign out', destroy_user_session_path %> </span>
    </div>
  <% end -%>

	<div class="span-24">
		<%= yield %>
	</div>

	<div class="span-24">
		<p class="quiet push-10">© 2010 Strata Labs. - </p>
	</div>

</div>

</body>
</html>